name: Publish to npmjs

permissions:
  id-token: write

on:
  release:
    types: [published]
  workflow_dispatch: # 允许通过 workflow_dispatch 触发

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 可根据需要修改 Node.js 版本
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build:lib

      - name: Prepare README for package
        run: |
          # 读取根目录的 README.md 内容
          README_CONTENT=$(cat README.md)
          # 调整图片路径，使其在包目录中正确显示
          MODIFIED_README=$(echo "$README_CONTENT" | sed 's|!\\[preview\\](/doc/img/preview.png)|!\\[preview\\](../../doc/img/preview.png)|g')
          # 确保包目录存在 (通常在 build 步骤后已存在)
          mkdir -p packages/simple-notation
          # 将修改后的 README 写入包目录
          echo "$MODIFIED_README" > packages/simple-notation/README.md

      - name: Publish to npmjs
        run: |
          cd packages/simple-notation
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
